version: "3.0"
services:
  webserver:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    container_name: trackr-www
    volumes:
      - ./src/backend:/var/www
    ports:
      - "8000:80"
    networks:
      - trackr_external
      - trackr_internal

  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
    container_name: trackr-php
    volumes:
      - ./src/backend:/var/www
    networks:
      - trackr_internal

  frontend:
    build:
      context: ./docker
      dockerfile: react.dockerfile
    container_name: trackr-front
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
    networks:
      - trackr_external
    tty: true

  # Need to revisit this another time.
  # The server needs to serve index.html if a requested file doesn't exist already (e.g. js/css resources)
  # frontend-build:
  #   build:
  #     context: ./docker
  #     dockerfile: build-server.dockerfile
  #   container_name: trackr-live
  #   volumes:
  #     - ./src/frontend/build:/app
  #   ports:
  #     - "3001:80"

  redis:
    image: redis:7
    container_name: trackr-redis
    volumes:
      - ./data/redis:/data
    networks:
      - trackr_internal

  mysql:
    image: mysql:8
    container_name: trackr-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - trackr_internal
      - trackr_external
    ports:
      - "8001:3306"
      
networks:
  trackr_external:
  trackr_internal:
