version: "3.0"
services:
  www:
    build:
      context: ./build
      dockerfile: nginx.dockerfile
    container_name: trackr-www
    volumes:
      - ./src:/var/www
    ports:
      - 10000:80
    networks:
      - trackr_external
      - trackr_internal

  php:
    build:
      context: ./build
      dockerfile: php.dockerfile
    container_name: trackr-php
    volumes:
      - ./src:/var/www
    networks:
      - trackr_internal

  redis:
    image: redis:7
    container_name: trackr-redis
    volumes:
      - ./data/redis:/data
    networks:
      - trackr_internal

  mysql:
    image: mysql:8
    container_name: trackr-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - trackr_internal
      
networks:
  trackr_external:
  trackr_internal:
