version: "3.0"
services:
  webserver:
    build:
      context: ./build
      dockerfile: nginx.dockerfile
    container_name: trackr-www
    volumes:
      - ./src/backend:/var/www
    ports:
      - "8000:80"
    networks:
      - trackr_external
      - trackr_internal

  php:
    build:
      context: ./build
      dockerfile: php.dockerfile
    container_name: trackr-php
    volumes:
      - ./src:/var/www
    networks:
      - trackr_internal

  frontend:
    build:
      context: ./build
      dockerfile: react.dockerfile
    container_name: trackr-front
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
    networks:
      - trackr_external
    tty: true

  redis:
    image: redis:7
    container_name: trackr-redis
    volumes:
      - ./data/redis:/data
    networks:
      - trackr_internal

  mysql:
    image: mysql:8
    container_name: trackr-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - trackr_internal
      
networks:
  trackr_external:
  trackr_internal:
